id = "midnight-harbor"
name = "Midnight Harbor"
version = "0.0.1"
schema_version = 1
description = "This theme is perfect for those who want a sleek and professional look for their editor."
repository = "https://github.com/iamngoni/midnight-harbor-theme"
authors = ["Ngonidzashe Mangudya <ngmangudya@gmail.com>"]
themes = ["themes/midnight-harbor.json"]
languages = []

[lib]

[grammars]

[language_servers]

[slash_commands]

[indexed_docs_providers]
